### ISSUE TITLE
Galaxy Emacs feature wishlist

### ISSUE THREAD

**Issue by taigacute** [hardcoreplayers/galaxy-emacs#34]
A wishlist of galaxy feautres.

**Comment by kernelzhen** [comment]
大佬 转战emacs了吗？

**Comment by taigacute** [comment]
我大概是70%是用日常桌面用emacs 30%要在服务器上写用vim。这样。

**Comment by kernelzhen** [comment]
你哪个thinkvim Mac可以不安装NerdFont吗？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Stephen"<notifications@github.com&gt;; 
发送时间: 2020年3月17日(星期二) 中午11:32
收件人: "hardcoreplayers/galaxy-emacs"<galaxy-emacs@noreply.github.com&gt;; 
抄送: "kernel"<361945949@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [hardcoreplayers/galaxy-emacs] Galaxy Emacs feature wishlist (#34)





 
我大概是70%是用日常桌面用emacs 30%要在服务器上写用vim。这样。

**Comment by taigacute** [comment]
可以，那你要把用的icon的地方去掉。

**Comment by kernelzhen** [comment]
[coc.nvim] Error on load extension coc-explorer from /Users/zivwong/.config/coc/extensions/node_modules/coc-explorer/lib/index.js: Error: Cannot find modu
le 'trash' &nbsp;怎么安装这个模块呢





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Stephen"<notifications@github.com&gt;; 
发送时间: 2020年3月17日(星期二) 中午11:51
收件人: "hardcoreplayers/galaxy-emacs"<galaxy-emacs@noreply.github.com&gt;; 
抄送: "kernel"<361945949@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [hardcoreplayers/galaxy-emacs] Galaxy Emacs feature wishlist (#34)





 
可以，那你要把用的icon的地方去掉。

**Comment by taigacute** [comment]
你npm挂掉了？用代理或者淘宝镜像。
